bot:
  token: 1213283991:AAE5saIjNRIu9sSAFF751qJRYjuhCZzX_bg
  username: FaMoneyBot

spring:
  r2dbc:
    username: postgres
    password: 123
    url: r2dbc:pool:postgresql://127.0.0.1:5433/family_money_db

