spring:
  r2dbc:
    username: ${FM_DB_USERNAME}
    password: ${FM_DB_PASSWORD}
    url: r2dbc:postgresql://${FM_DB_HOST}:${FM_DB_PORT}/${FM_DB_SCHEMA}

sessionbot:
  telegram:
    token: ${FM_BOT_TOKEN}
    bot-username: ${FM_BOT_USERNAME}

