version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: family-money-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080