server:
  port: 9093
spring:
  application:
    name: family-money-categories
  data:
    mongodb:
      host: 192.168.1.135
      port: 27017
      database: categories
      username: mongo
      password: 123
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.135:8761/eureka